### ISSUE TITLE
Rule Clarification

### ISSUE THREAD

**Issue by steinauer** [Jeadie/liars-dice#1]
Hi Jeadie, 

Nice work!

Just with the "exact" rule. If you're correct you gain 1 die, and incorrect you lose 2. Makes it a high risk move and keeps the value of dice very high. 

Also did you consider including the "1" as a joker rule if you remember, if it isn't too hard to implement. 

I've written out a Mandarin translation of the rules for you as well. 
[Liars dice 中文翻译 - 吹牛.txt](https://github.com/Jeadie/liars-dice/files/10045647/Liars.dice.-.txt)

Regards,
Steinauer

**Comment by Jeadie** [comment]
Thank you so much. I'll add the mandarin translation. 

I included the "1" as a joker rule already, I just forgot to mention it. I'll add it to the README.md

**Comment by Jeadie** [comment]
I've update the README with both:
- "1" Joker rule
- A reference to the Chinese translation of the rules. 

Feel free to open a PR to update the Chinese translation with the "1" joker rule.
